### PR TITLE
Make compatible with Python 3

### LINKED ISSUE #1: zcrmsdk import does not work
First I tried to just call `ZCRMRestClient.initialize()` which did not work:

~~~
>>> ZCRMRestClient.initialize() 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'ZCRMRestClient' is not defined
~~~

Second I tried to import the `zcrmsdk` and got the following error:

~~~
>>> import zcrmsdk
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/zcrmsdk/__init__.py", line 7, in <module>
    from RestClient import ZCRMRestClient
ImportError: No module named 'RestClient'
~~~

However, `RestClient.py` exists:

~~~
/usr/local/lib/python3.5/dist-packages/zcrmsdk# ls
CLException.py   Operations.py   Request.py     Utility.py
Handler.py       Org.py          Response.py    __init__.py
OAuthClient.py   Path.py         RestClient.py  __pycache__
OAuthUtility.py  Persistence.py  Test.py        resources
~~~

Do I miss anything?

### PR DESCRIPTION
**Pull request by sp0gg**
This PR changes all imports to relative imports and removes references to the `long` function which does not exist in Python 3. The package will now run on Python 3. Fixes #1.

### CODE REVIEW

**Comment by Jeeppler** [comment]
Zoho: Please merge this PR.

**Comment by sp0gg** [comment]
If you can't afford to wait until Zoho merges this PR and publishes the update to PyPI, you can always fork my repo and pip install from your fork.

`pip install https://github.com/<your username>/zcrm-python-sdk/archive/<branch name>.zip`

**Comment by Jeeppler** [comment]
@sp0gg Why did you close the pull request?

**Comment by sp0gg** [comment]
@Jeeppler Zoho merged in their own changes addressing this issue, and I am no longer working with the Zoho API to keep up with it.

**Comment by Jeeppler** [comment]
@sp0gg thanks for the clarification.

**Pull request closed without merging**
